apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: gatekeeper-system
spec:
  sync:
    syncOnly:
    - group: ""
      version: v1
      kind: Namespace
    - group: ""
      version: v1
      kind: Pod
    - group: apps
      version: v1
      kind: ReplicaSet
    - group: extensions
      version: v1beta1
      kind: ReplicaSet
