apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LinkerdMutualTLS
metadata:
  name: v0.0.1
  labels:
    policy.linkerd.io: mtls
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
      - key: config.linkerd.io/admission-webhooks
        operator: NotIn
        values: ["disabled"]
  parameters:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        linkerd.io/identity-mode: default
    proxy:
      name: linkerd-proxy
      env:
      - name: LINKERD2_PROXY_LOG
        value: warn,linkerd2_proxy=info
      - name: LINKERD2_PROXY_DESTINATION_SVC_ADDR
        value: linkerd-dst.linkerd.svc.cluster.local:8086
      - name: LINKERD2_PROXY_CONTROL_LISTEN_ADDR
        value: 0.0.0.0:4190
      - name: LINKERD2_PROXY_ADMIN_LISTEN_ADDR
        value: 0.0.0.0:4191
      - name: LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR
        value: 127.0.0.1:4140
      - name: LINKERD2_PROXY_INBOUND_LISTEN_ADDR
        value: 0.0.0.0:4143
      - name: LINKERD2_PROXY_DESTINATION_GET_SUFFIXES
        value: svc.cluster.local.
      - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
        value: svc.cluster.local.
      - name: LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE
        value: 10000ms
      - name: LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE
        value: 10000ms
      - name: _pod_ns
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: LINKERD2_PROXY_DESTINATION_CONTEXT
        value: ns:$(_pod_ns)
      - name: LINKERD2_PROXY_IDENTITY_DIR
        value: /var/run/linkerd/identity/end-entity
      - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
        value: |
          -----BEGIN CERTIFICATE-----
          MIIBgjCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
          eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMTkxMDIyMDMyMzUxWhcNMjAxMDIx
          MDMyNDExWjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
          YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARp+uRJ/GHvYXNjoGbVo5XugsAH
          KCUDQ3mFlOVLGdK2XcZWOTxW9QfAUYPGxcPiUIZN751Wuj2zadam08rzWQVfo0Iw
          QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
          MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDRwAwRAIgF3yjE0IPMhUG+oXD
          OawE1VifG4LZBTi0oJe6I7HD6tACIH4sciKhokMWbhY6w6wro5KC1NJQxYYYCHI1
          ClsEMDmF
          -----END CERTIFICATE-----
      - name: LINKERD2_PROXY_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/kubernetes.io/serviceaccount/token
      - name: LINKERD2_PROXY_IDENTITY_SVC_ADDR
        value: linkerd-identity.linkerd.svc.cluster.local:8080
      - name: _pod_sa
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName
      - name: _l5d_ns
        value: linkerd
      - name: _l5d_trustdomain
        value: cluster.local
      - name: LINKERD2_PROXY_IDENTITY_LOCAL_NAME
        value: $(_pod_sa).$(_pod_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
      - name: LINKERD2_PROXY_IDENTITY_SVC_NAME
        value: linkerd-identity.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
      - name: LINKERD2_PROXY_DESTINATION_SVC_NAME
        value: linkerd-destination.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
      - name: LINKERD2_PROXY_TAP_SVC_NAME
        value: linkerd-tap.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
      volumeMounts:
      - mountPath: /var/run/linkerd/identity/end-entity
        name: linkerd-identity-end-entity
